<h1> Soal 1: Pemahaman Tentang Model Evaluasi</h1>

Jawab pertanyaan di bawah ini dengan bahasa masing-masing?

1. Apa perbedaan antara data latih, data validasi, dan data test?
2. Bagaimana cara kita menilai performa suatu model?
3. Apa itu Confusion Matrix? Jelaskan secara lengkap!
4. Apa itu Classification Report dari sklearn?

Jawab:
1. data latih adalah data yang digunakan untuk melatih model, data validasi adalah data yang digunakan untuk mengecek akurasi dari model, data test adalah data yang digunakan untuk mengetes model
2. dengan menggunakan confusion matrix
3. Confusion matrix juga sering disebut error matrix. Pada dasarnya confusion matrix memberikan informasi perbandingan hasil klasifikasi yang dilakukan oleh sistem (model) dengan hasil klasifikasi sebenarnya. Confusion matrix berbentuk tabel matriks yang menggambarkan kinerja model klasifikasi pada serangkaian data uji yang nilai sebenarnya diketahui. 
4. Sebuah library yang menampilkan report berupa precision, recall, dan f1 dari model yang kita buat

---

<h1>Soal 2: Aplikasi Model Evaluasi</h1>

Kali ini kita akan menggunakan data untuk memprediksi kelangsungan hidup pasien yang telah mengalami operasi payudara. Dengan informasi yang dimiliki terkait pasien, kita akan membuat model untuk memprediksi apakah pasien akan bertahan hidup dalam waktu lebih dari 5 tahun atau tidak.

Lebih Lengkapnya kalian bisa membaca informasi tentang dataset di link berikut: https://raw.githubusercontent.com/jbrownlee/Datasets/master/haberman.names

Buat model Klasifikasi (Model/Algoritma Bebas) untuk memprediksi status pasien dengan ketentuan sebagai berikut:

1. Bagi kedua data ini menjadi data training dan data test dengan test_size=0.25.
3. Pelajar tentang metrics roc_auc_score kemudian buatlah model dan evaluasi dengan menggunakan teknik cross-validation dengan scoring 'roc_auc'. Baca https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_score.html untuk menggunakan metric roc_auc saat cross-validation.
3. Berapa score rata2 dari model dengan teknik cross-validation tersebut?
4. Prediksi data test dengan model yang telah kalian buat!
5. Bagaimana hasil confusion matrix dari hasil prediksi tersebut?
6. Bagaimana classification report dari hasil prediksi tersebut?
5. Seberapa baik model anda dalam memprediksi seorang pasien mempunyai status positive?
6. Seberapa baik model anda dalam memprediksi seorang pasien mempunyai status negatif?

In [1]:
import pandas as pd

url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/haberman.csv'
list_cols = ['Age', "Patient's Years", "N_positive_ax", "survival_status"]
df = pd.read_csv(url, names=list_cols)

In [3]:
df.head()

Age  Patient's Years  N_positive_ax  survival_status
0   30               64              1                1
1   30               62              3                1
2   30               65              0                1
3   31               59              2                1
4   31               65              4                1

In [86]:
df['survival_status'].value_counts()

1    225
2     81
Name: survival_status, dtype: int64

In [166]:
# Code here
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

X = df.drop('survival_status', axis=1)
y = df['survival_status']

# 1 Bagi kedua data ini menjadi data training dan data test dengan test_size=0.25
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=21, stratify=y)

model = KNeighborsClassifier(n_neighbors=13)
model.fit(X_train, y_train)

# 2 # 3 Berapa score rata2 dari model dengan teknik cross-validation tersebut?
cross = cross_val_score(model, X_train, y_train).mean()
print(f'Score Rata-Rata: {cross}')

# 4 Prediksi data test dengan model yang telah kalian buat!
y_pred = model.predict(X_test)
print(y_predict)

# 5 Bagaimana hasil confusion matrix dari hasil prediksi tersebut?
conf_m = confusion_matrix(y_test, y_predict, labels=[2,1])
print(conf_m)

# 6 Bagaimana classification report dari hasil prediksi tersebut?
print(classification_report(y_test, y_pred))

# 7 Seberapa baik model anda dalam memprediksi seorang pasien mempunyai status positive?
# kurang baik

# 8 Seberapa baik model anda dalam memprediksi seorang pasien mempunyai status negatif?
# kurang baik

Score Rata-Rata: 0.7513043478260869
[1 1 1 2 1 1 2 1 1 1 2 1 1 1 1 1 1 1 1 2 1 1 1 2 1 1 2 2 2 1 1 2 1 1 2 1 1
 1 2 1 1 2 1 1 1 1 1 1 1 2 1 1 1 1 2 1 1 2 1 2 1 1 1 1 2 1 1 1 2 1 2 1 1 2
 1 1 2]
[[ 7 13]
 [14 43]]
              precision    recall  f1-score   support

           1       0.80      0.86      0.83        57
           2       0.50      0.40      0.44        20

    accuracy                           0.74        77
   macro avg       0.65      0.63      0.64        77
weighted avg       0.72      0.74      0.73        77



---

<h1> Soal 3: Pemahaman Tentang Model Selection</h1>

Jelaskan dengan bahasa sendiri!

1. Apa itu Bias dan Variance?
2. Apa itu Overfitting dan Underfitting?
3. Apa yang bisa kita lakukan untuk mengatur kompleksitas dari model?
4. Bagaimana model yang baik?
5. Kapan kita menggunakan GridSearchcv dan kapan menggunakan RandomizedSearchCV?

Jawab:
1. Bias adalah perbedaan nilai prediksi dengan nilai yang sebenarnya, Variance adalah variabel dari prediksi model untuk data tertentu dimana memberikan kita informasi perserbaran data kita
2. Overfitting adalah kondisi dimana error rendah saat training tetapi error tinggi saat test, sedangkan Underfitting adalah kondisi dimana error tinggi saat proses training dan test
3. Dengan melakukan tuning pada hyperparameter model yang digunakan
4. Model yang dapat memprediksi data yang belum dilihat setelah belajar daru data training
5. GridSearchCV digunakan saat kita ingin menemukan parameter yang paling optimal, sedangkan RandomizedSearchCV digunakan jika ingin lebih cepat dalam memilih parameter yang baik tetapi hasilnya kurang optimal

---

<h1> Soal 4: Aplikasi Model Selection</h1>

1. Bagi kedua data berikut ini menjadi data training dan data test dengan test_size=0.25.
2. Gunakan algoritma KNN sebagai model classifier.
3. Gunakan fungsi GridSearchCV untuk hyperparameter tuning dan model selection.
4. jumlah fold bebas!, gunakan scoring 'roc_auc'
5. Definisikan kombinasi hyperparameter untuk model selection dengan GridSearchCV. kombinasi Hyperparameter bebas, baca lagi dokumentasi KNN di link berikut https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html untuk memahami lagi jenis2 hyperparameter di algorithma KNN.
6. Latih model terhadap data training.
7. Apa hyperparameter terbaik untuk kombinasi hyperparameter kalian?
8. Berapa score validasi terbaik dari model tersebut?
9. Prediksi probabilitasi output dari model yang telah di buat terhadap data test. note : gunakan method .predict_proba() untuk menghasilkan output probabilitas
10. Perhatikan bahwa hasil prediksi ada 2, dimana masing2 adalah nilai probabilitas untuk setiap class label. Ambil nilai probabilitas pasien phositive meninggal dalam waktu kurang dari 5 tahun. note : gunakan bantuan attirubte .classes_ untuk mengetahui urutan label dari hasil prediksi probabilitas.
11. Berapa nilai score roc_auc untuk data test?
12. Apakah model anda termasuk baik, overtting, atau underfitting?
13. Ulangi tahap di atas namun kali ini menggunakan algoritma DecisionTreeClassifier dan kalian bisa menggunakan RandomizedSearchCV apabila process training lama. pelajari algoritma DecisionTreeClassifier di linkberikut: https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html?highlight=decisiontreeclassifier#sklearn.tree.DecisionTreeClassifier
14. Bandingkan scorenya dengan Algoritma KNN, mana yang lebih baik?

Note : Data Science adalah experiment, sangat di dimungkinkan memerlukan beberapa kali percobaan untuk mendapatkan hasil yang terbaik! Happy Coding :)

In [93]:
import pandas as pd

url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/haberman.csv'
list_cols = ['Age', "Patient's Years", "N_positive_ax", "survival_status"]
df = pd.read_csv(url, names=list_cols)

In [94]:
df.head()

Age  Patient's Years  N_positive_ax  survival_status
0   30               64              1                1
1   30               62              3                1
2   30               65              0                1
3   31               59              2                1
4   31               65              4                1

In [142]:
# Code here
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import roc_auc_score
import numpy as np

X = df.drop('survival_status', axis=1)
y = df['survival_status']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=21, stratify=y)

model = KNeighborsClassifier()
param_grid = {'n_neighbors':np.arange(5,50), 'weights':['distance', 'uniform']}

gscv = GridSearchCV(model, param_grid, scoring='roc_auc', cv=10)
gscv.fit(X_train, y_train)

GridSearchCV(cv=10, error_score=nan,
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=5, p=2,
                                            weights='uniform'),
             iid='deprecated', n_jobs=None,
             param_grid={'n_neighbors': array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
                         'weights': ['distance', 'uniform']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='roc_auc', verbose=0)

In [144]:
gscv.best_params_

{'n_neighbors': 8, 'weights': 'distance'}

In [145]:
gscv.best_score_

0.7094012605042017

In [146]:
gscv.classes_

array([1, 2], dtype=int64)

In [189]:
probab = gscv.predict_proba(X_test)[:,1]
probab

array([0.1603243 , 0.20883415, 0.36538442, 1.        , 0.32277369,
       0.        , 0.46636001, 0.27062309, 0.14562671, 0.32277369,
       1.        , 0.        , 0.27180523, 0.        , 0.15843893,
       0.35906162, 0.14465703, 0.31355109, 0.        , 0.53374431,
       0.44825406, 0.15843893, 0.        , 0.65405186, 0.        ,
       0.        , 0.3479835 , 0.41124937, 0.45972325, 0.24717422,
       0.        , 1.        , 0.23923218, 0.09089058, 0.73488259,
       0.22442009, 0.12260191, 0.10427116, 0.43376177, 0.22107108,
       0.49051021, 0.4417585 , 0.27955334, 0.4618577 , 0.13815895,
       0.        , 0.        , 0.08888316, 0.13430542, 0.88106452,
       0.27734122, 0.51159375, 0.4652136 , 0.11246145, 0.49222287,
       0.        , 0.19253033, 0.39296917, 0.        , 0.88783049,
       0.39574849, 0.25320622, 0.12170658, 0.        , 0.26178135,
       0.13697051, 0.34473297, 0.11447661, 0.63332535, 0.        ,
       0.65799749, 0.263332  , 0.        , 0.86724282, 0.26461

In [179]:
y_predik = gscv.predict(X_test)
roc_auc_score(y_test, y_predik)

0.5885964912280702

In [181]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import RandomizedSearchCV

model_tree = DecisionTreeClassifier()
param_grid_tree = {'random_state':np.arange(0,50), 'splitter':['best','random']}

rscv = RandomizedSearchCV(model_tree, param_grid_tree, scoring='roc_auc', cv=10)
rscv.fit(X_train, y_train)

RandomizedSearchCV(cv=10, error_score=nan,
                   estimator=DecisionTreeClassifier(ccp_alpha=0.0,
                                                    class_weight=None,
                                                    criterion='gini',
                                                    max_depth=None,
                                                    max_features=None,
                                                    max_leaf_nodes=None,
                                                    min_impurity_decrease=0.0,
                                                    min_impurity_split=None,
                                                    min_samples_leaf=1,
                                                    min_samples_split=2,
                                                    min_weight_fraction_leaf=0.0,
                                                    presort='deprecated',
                                                    random_state=None,
         

In [182]:
rscv.best_params_

{'splitter': 'random', 'random_state': 29}

In [183]:
rscv.best_score_

0.6050682773109244

In [184]:
rscv.classes_

array([1, 2], dtype=int64)

In [187]:
probab2 = rscv.predict_proba(X_test)[:,1]
probab2

array([0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0.,
       1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0.,
       1., 0., 1., 0., 0., 0., 0., 0., 1.])

In [190]:
y_predik = rscv.predict(X_test)
roc_auc_score(y_test, y_predik)

0.46842105263157896

# KNN LEBIH BAIK